# -*- coding: utf-8 -*-
"""Source unique du contenu vocal — génère voiceContent.json.

Le champ `icon` est un NOM d'icône SVG (voir src/components/Icon.tsx),
plus aucun emoji : rendu identique partout, jamais lu par la synthèse vocale.
"""
import json, os

COMPTINES = [
 ("frere-jacques","Frère Jacques","bell","#E53935","#B71C1C",
  ["Frère Jacques, Frère Jacques,","Dormez-vous ? Dormez-vous ?",
   "Sonnez les matines !","Sonnez les matines !","Din, din, don !  Din, din, don !"],
  [261.6,293.7,329.6,261.6,329.6,392.0,392.0,261.6]),
 ("promenons-nous","Promenons-nous dans les bois","wolf","#388E3C","#1B5E20",
  ["Promenons-nous dans les bois,","Pendant que le loup n'y est pas.",
   "Si le loup y était,","Il nous mangerait !","Mais comme il n'y est pas,","Il nous mangera pas !"],
  [261.6,329.6,392.0,440.0,392.0,329.6,261.6,261.6]),
 ("petit-navire","Il était un petit navire","sailboat","#1565C0","#0D47A1",
  ["Il était un petit navire,","Il était un petit navire,",
   "Qui n'avait ja, jamais navigué,","Qui n'avait ja, jamais navigué,","Ohé ! Ohé ! 🌊"],
  [329.6,392.0,440.0,523.2,440.0,392.0,329.6,293.7]),
 ("ainsi-font","Ainsi font les marionnettes","party","#7B1FA2","#4A148C",
  ["Ainsi font, font, font,","Les petites marionnettes,","Ainsi font, font, font,",
   "Trois p'tits tours et puis s'en vont !","Les mains font, font, font,","Les bras font, font, font… ✨"],
  [392.0,440.0,523.2,440.0,392.0,329.6,293.7,261.6]),
 ("furet","Il court, il court le furet","rabbit","#E65100","#BF360C",
  ["Il court, il court le furet,","Le furet du bois, mesdames !","Il court, il court le furet,",
   "Le furet du bois joli.","Il a passé par ici,","Il repassera par là !"],
  [261.6,329.6,261.6,392.0,329.6,261.6,440.0,392.0]),
 ("alouette","Alouette","bird","#00897B","#004D40",
  ["Alouette, gentille alouette,","Alouette, je te plumerai.","Je te plumerai la tête,",
   "Je te plumerai la tête,","Et la tête ! Et la tête !","Alouette ! Oh ! 🎵"],
  [261.6,329.6,392.0,329.6,261.6,392.0,329.6,261.6]),
 ("pont-avignon","Sur le pont d'Avignon","bridge","#C0392B","#922B21",
  ["Sur le pont d'Avignon,","On y danse, on y danse,","Sur le pont d'Avignon,",
   "On y danse tous en rond.","Les belles dames font comme ça,","Et puis encore comme ça ! 💃"],
  [392.0,440.0,392.0,349.2,329.6,293.7,261.6,293.7]),
 ("bateau-eau","Bateau sur l'eau","rowboat","#1976D2","#0D47A1",
  ["Bateau sur l'eau,","La rivière, la rivière,","Bateau sur l'eau,",
   "La rivière au bord de l'eau.","Il a fait naufrage,","Patatras, dans l'eau ! 💦"],
  [440.0,392.0,349.2,329.6,293.7,261.6,293.7,329.6]),
 ("planter-choux","Savez-vous planter les choux","cabbage","#558B2F","#33691E",
  ["Savez-vous planter les choux,","À la mode, à la mode ?","Savez-vous planter les choux,",
   "À la mode de chez nous ?","On les plante avec les pieds,","À la mode de chez nous ! 🌱"],
  [261.6,329.6,392.0,440.0,392.0,329.6,261.6,293.7]),
 ("claire-fontaine","À la claire fontaine","drop","#0288D1","#01579B",
  ["À la claire fontaine,","M'en allant promener,","J'ai trouvé l'eau si belle,",
   "Que je m'y suis baigné.","Il y a longtemps que je t'aime,","Jamais je ne t'oublierai. 💙"],
  [261.6,293.7,329.6,392.0,349.2,329.6,293.7,261.6]),
]

HISTOIRES = [
 ("petit-chat","Le petit chat curieux","cat","#FF9800","#E65100",
  [("cat","Il était une fois un petit chat tout doux qui s'appelait Minou."),
   ("tree","Un matin, Minou sortit dans le jardin. Le soleil brillait très fort."),
   ("butterfly","Il vit un joli papillon bleu qui dansait dans les fleurs."),
   ("flower","Minou voulut jouer avec lui. Il sauta, sauta, encore et encore !"),
   ("smile","Le papillon se posa sur son nez. Minou ferma les yeux et ronronna."),
   ("heart","Et le soir, Minou s'endormit, heureux de sa belle journée. Bonne nuit, Minou !")]),
 ("etoile","La petite étoile","star","#3F51B5","#1A237E",
  [("star","Tout là-haut dans le ciel vivait une petite étoile qui brillait."),
   ("moon","La nuit, elle veillait sur tous les enfants endormis."),
   ("sparkle","Elle envoyait sa douce lumière par la fenêtre, comme un câlin."),
   ("sleepy","Quand un enfant avait peur, l'étoile clignait pour le rassurer."),
   ("star","« Dors tranquille », disait-elle. « Je suis là, je te protège. »"),
   ("heart","Et chaque matin, l'étoile s'endormait, contente d'avoir veillé. Doux rêves !")]),
 ("ours","Le gros ours câlin","bear","#795548","#3E2723",
  [("bear","Dans la forêt vivait un gros ours tout doux qui adorait les câlins."),
   ("pine","Chaque jour, il se promenait entre les grands arbres verts."),
   ("honey","Il aimait beaucoup le miel doré, sucré et délicieux."),
   ("bee","Les abeilles étaient ses amies. Elles bourdonnaient autour de lui."),
   ("feeling-hug","Le soir, l'ours faisait un grand câlin à tous ses amis de la forêt."),
   ("sleepy","Puis il se blottissait dans sa grotte bien chaude pour dormir. À demain !")]),
 ("bateau","Le petit bateau","sailboat","#00ACC1","#006064",
  [("sailboat","Il y avait un petit bateau blanc qui voguait sur la mer bleue."),
   ("wave","Les vagues le berçaient doucement, comme un berceau."),
   ("dolphin","Des dauphins joueurs nageaient tout autour en sautant dans l'eau."),
   ("fish","Sous la mer, des poissons colorés brillaient comme des bijoux."),
   ("sunset","Le soleil se couchait, peignant le ciel en rose et orange."),
   ("anchor","Le petit bateau rentra au port, fatigué mais heureux. Quelle belle journée !")]),
 ("grenouille","La petite grenouille verte","frog","#43A047","#1B5E20",
  [("frog","Dans la mare vivait une toute petite grenouille bien verte et bien douce."),
   ("leaf","Chaque matin, elle sautait de nénuphar en nénuphar en chantant."),
   ("bee","Elle attrapait les moustiques avec sa longue et rapide langue rose."),
   ("umbrella","Quand il pleuvait, elle levait la tête et criait : « Coâ, coâ, coâ ! »"),
   ("sun","Et quand le soleil revenait, elle s'étirait doucement sur sa grande feuille."),
   ("heart","La petite grenouille était heureuse, reine de sa jolie mare. Coâ !")]),
 ("lapin","Le lapin du jardin","rabbit","#F06292","#880E4F",
  [("rabbit","Dans le grand jardin vivait un lapin aux longues oreilles blanches et douces."),
   ("carrot","Il adorait grignoter les carottes oranges et les feuilles de salade."),
   ("flower","Il courait parmi les fleurs colorées en faisant de grands bonds joyeux."),
   ("bird","Les oiseaux chantaient et le lapin écoutait, les oreilles bien dressées."),
   ("moon","Le soir, il rentrait dans son terrier bien douillet et bien chaud."),
   ("rabbit","Bonne nuit, petit lapin ! Demain, de nouvelles aventures t'attendent !")]),
 ("coccinelle","La coccinelle voyageuse","ladybug","#E53935","#B71C1C",
  [("ladybug","Il y avait une belle coccinelle rouge avec sept points noirs sur le dos."),
   ("flower","Elle aimait voler de fleur en fleur dans le jardin ensoleillé."),
   ("cloud","Un jour, le vent l'emporta très loin, très haut au-dessus des nuages."),
   ("rainbow","Elle vit un magnifique arc-en-ciel et des prairies dorées à perte de vue."),
   ("home","Mais son cœur lui disait : « Rentre chez toi, c'est là que tu es heureuse. »"),
   ("flower","La coccinelle revint au jardin, plus heureuse que jamais d'être à la maison !")]),
 ("nuage","Le petit nuage blanc","cloud","#5C6BC0","#283593",
  [("cloud","Haut dans le ciel bleu flottait un tout petit nuage blanc et doux."),
   ("cloud","Le vent le promenait doucement au-dessus des maisons et des prés verts."),
   ("drop","Quand les fleurs avaient soif, le nuage leur envoyait de la pluie douce."),
   ("flower","Les fleurs levaient la tête, souriaient et disaient merci au petit nuage."),
   ("sunset","Au coucher du soleil, le nuage devenait rose, puis orange, puis violet."),
   ("star","Et la nuit, le nuage se reposait, bercé tendrement par les étoiles. Dors bien !")]),
]

comptines = [{"id":i,"title":t,"icon":e,"primary":p,"secondary":s,"lines":l,"melody":m}
             for (i,t,e,p,s,l,m) in COMPTINES]
histoires = [{"id":i,"title":t,"icon":e,"primary":p,"secondary":s,
              "pages":[{"icon":pe,"text":px} for (pe,px) in pg]}
             for (i,t,e,p,s,pg) in HISTOIRES]

out = {"comptines":comptines,"histoires":histoires}
dst = os.path.join(os.path.dirname(__file__),"..","src","data","voiceContent.json")
with open(dst,"w",encoding="utf-8") as f:
    json.dump(out,f,ensure_ascii=False,indent=2)
print("voiceContent.json écrit :", len(comptines),"comptines,",len(histoires),"histoires")
