# -*- coding: utf-8 -*-
"""Source unique du contenu vocal — génère voiceContent.json."""
import json, os

COMPTINES = [
 ("frere-jacques","Frère Jacques","🔔","#E53935","#B71C1C",
  ["Frère Jacques, Frère Jacques,","Dormez-vous ? Dormez-vous ?",
   "Sonnez les matines !","Sonnez les matines !","Din, din, don !  Din, din, don !"],
  [261.6,293.7,329.6,261.6,329.6,392.0,392.0,261.6]),
 ("promenons-nous","Promenons-nous dans les bois","🐺","#388E3C","#1B5E20",
  ["Promenons-nous dans les bois,","Pendant que le loup n'y est pas.",
   "Si le loup y était,","Il nous mangerait !","Mais comme il n'y est pas,","Il nous mangera pas !"],
  [261.6,329.6,392.0,440.0,392.0,329.6,261.6,261.6]),
 ("petit-navire","Il était un petit navire","⛵","#1565C0","#0D47A1",
  ["Il était un petit navire,","Il était un petit navire,",
   "Qui n'avait ja, jamais navigué,","Qui n'avait ja, jamais navigué,","Ohé ! Ohé ! 🌊"],
  [329.6,392.0,440.0,523.2,440.0,392.0,329.6,293.7]),
 ("ainsi-font","Ainsi font les marionnettes","🎭","#7B1FA2","#4A148C",
  ["Ainsi font, font, font,","Les petites marionnettes,","Ainsi font, font, font,",
   "Trois p'tits tours et puis s'en vont !","Les mains font, font, font,","Les bras font, font, font… ✨"],
  [392.0,440.0,523.2,440.0,392.0,329.6,293.7,261.6]),
 ("furet","Il court, il court le furet","🐾","#E65100","#BF360C",
  ["Il court, il court le furet,","Le furet du bois, mesdames !","Il court, il court le furet,",
   "Le furet du bois joli.","Il a passé par ici,","Il repassera par là !"],
  [261.6,329.6,261.6,392.0,329.6,261.6,440.0,392.0]),
 ("alouette","Alouette","🐦","#00897B","#004D40",
  ["Alouette, gentille alouette,","Alouette, je te plumerai.","Je te plumerai la tête,",
   "Je te plumerai la tête,","Et la tête ! Et la tête !","Alouette ! Oh ! 🎵"],
  [261.6,329.6,392.0,329.6,261.6,392.0,329.6,261.6]),
 ("pont-avignon","Sur le pont d'Avignon","🌉","#C0392B","#922B21",
  ["Sur le pont d'Avignon,","On y danse, on y danse,","Sur le pont d'Avignon,",
   "On y danse tous en rond.","Les belles dames font comme ça,","Et puis encore comme ça ! 💃"],
  [392.0,440.0,392.0,349.2,329.6,293.7,261.6,293.7]),
 ("bateau-eau","Bateau sur l'eau","🚣","#1976D2","#0D47A1",
  ["Bateau sur l'eau,","La rivière, la rivière,","Bateau sur l'eau,",
   "La rivière au bord de l'eau.","Il a fait naufrage,","Patatras, dans l'eau ! 💦"],
  [440.0,392.0,349.2,329.6,293.7,261.6,293.7,329.6]),
 ("planter-choux","Savez-vous planter les choux","🥬","#558B2F","#33691E",
  ["Savez-vous planter les choux,","À la mode, à la mode ?","Savez-vous planter les choux,",
   "À la mode de chez nous ?","On les plante avec les pieds,","À la mode de chez nous ! 🌱"],
  [261.6,329.6,392.0,440.0,392.0,329.6,261.6,293.7]),
 ("claire-fontaine","À la claire fontaine","💧","#0288D1","#01579B",
  ["À la claire fontaine,","M'en allant promener,","J'ai trouvé l'eau si belle,",
   "Que je m'y suis baigné.","Il y a longtemps que je t'aime,","Jamais je ne t'oublierai. 💙"],
  [261.6,293.7,329.6,392.0,349.2,329.6,293.7,261.6]),
]

HISTOIRES = [
 ("petit-chat","Le petit chat curieux","🐱","#FF9800","#E65100",
  [("🐱","Il était une fois un petit chat tout doux qui s'appelait Minou."),
   ("🌳","Un matin, Minou sortit dans le jardin. Le soleil brillait très fort."),
   ("🦋","Il vit un joli papillon bleu qui dansait dans les fleurs."),
   ("🌸","Minou voulut jouer avec lui. Il sauta, sauta, encore et encore !"),
   ("😺","Le papillon se posa sur son nez. Minou ferma les yeux et ronronna."),
   ("❤️","Et le soir, Minou s'endormit, heureux de sa belle journée. Bonne nuit, Minou !")]),
 ("etoile","La petite étoile","⭐","#3F51B5","#1A237E",
  [("⭐","Tout là-haut dans le ciel vivait une petite étoile qui brillait."),
   ("🌙","La nuit, elle veillait sur tous les enfants endormis."),
   ("✨","Elle envoyait sa douce lumière par la fenêtre, comme un câlin."),
   ("😴","Quand un enfant avait peur, l'étoile clignait pour le rassurer."),
   ("🌟","« Dors tranquille », disait-elle. « Je suis là, je te protège. »"),
   ("💙","Et chaque matin, l'étoile s'endormait, contente d'avoir veillé. Doux rêves !")]),
 ("ours","Le gros ours câlin","🐻","#795548","#3E2723",
  [("🐻","Dans la forêt vivait un gros ours tout doux qui adorait les câlins."),
   ("🌲","Chaque jour, il se promenait entre les grands arbres verts."),
   ("🍯","Il aimait beaucoup le miel doré, sucré et délicieux."),
   ("🐝","Les abeilles étaient ses amies. Elles bourdonnaient autour de lui."),
   ("🤗","Le soir, l'ours faisait un grand câlin à tous ses amis de la forêt."),
   ("💤","Puis il se blottissait dans sa grotte bien chaude pour dormir. À demain !")]),
 ("bateau","Le petit bateau","⛵","#00ACC1","#006064",
  [("⛵","Il y avait un petit bateau blanc qui voguait sur la mer bleue."),
   ("🌊","Les vagues le berçaient doucement, comme un berceau."),
   ("🐬","Des dauphins joueurs nageaient tout autour en sautant dans l'eau."),
   ("🐟","Sous la mer, des poissons colorés brillaient comme des bijoux."),
   ("🌅","Le soleil se couchait, peignant le ciel en rose et orange."),
   ("⚓","Le petit bateau rentra au port, fatigué mais heureux. Quelle belle journée !")]),
 ("grenouille","La petite grenouille verte","🐸","#43A047","#1B5E20",
  [("🐸","Dans la mare vivait une toute petite grenouille bien verte et bien douce."),
   ("🌿","Chaque matin, elle sautait de nénuphar en nénuphar en chantant."),
   ("🦟","Elle attrapait les moustiques avec sa longue et rapide langue rose."),
   ("☔","Quand il pleuvait, elle levait la tête et criait : « Coâ, coâ, coâ ! »"),
   ("🌞","Et quand le soleil revenait, elle s'étirait doucement sur sa grande feuille."),
   ("💚","La petite grenouille était heureuse, reine de sa jolie mare. Coâ !")]),
 ("lapin","Le lapin du jardin","🐰","#F06292","#880E4F",
  [("🐰","Dans le grand jardin vivait un lapin aux longues oreilles blanches et douces."),
   ("🥕","Il adorait grignoter les carottes oranges et les feuilles de salade."),
   ("🌺","Il courait parmi les fleurs colorées en faisant de grands bonds joyeux."),
   ("🐦","Les oiseaux chantaient et le lapin écoutait, les oreilles bien dressées."),
   ("🌙","Le soir, il rentrait dans son terrier bien douillet et bien chaud."),
   ("🐾","Bonne nuit, petit lapin ! Demain, de nouvelles aventures t'attendent !")]),
 ("coccinelle","La coccinelle voyageuse","🐞","#E53935","#B71C1C",
  [("🐞","Il y avait une belle coccinelle rouge avec sept points noirs sur le dos."),
   ("🌻","Elle aimait voler de fleur en fleur dans le jardin ensoleillé."),
   ("☁️","Un jour, le vent l'emporta très loin, très haut au-dessus des nuages."),
   ("🌈","Elle vit un magnifique arc-en-ciel et des prairies dorées à perte de vue."),
   ("🏠","Mais son cœur lui disait : « Rentre chez toi, c'est là que tu es heureuse. »"),
   ("🌺","La coccinelle revint au jardin, plus heureuse que jamais d'être à la maison !")]),
 ("nuage","Le petit nuage blanc","☁️","#5C6BC0","#283593",
  [("☁️","Haut dans le ciel bleu flottait un tout petit nuage blanc et doux."),
   ("🌬️","Le vent le promenait doucement au-dessus des maisons et des prés verts."),
   ("🌧️","Quand les fleurs avaient soif, le nuage leur envoyait de la pluie douce."),
   ("🌸","Les fleurs levaient la tête, souriaient et disaient merci au petit nuage."),
   ("🌅","Au coucher du soleil, le nuage devenait rose, puis orange, puis violet."),
   ("⭐","Et la nuit, le nuage se reposait, bercé tendrement par les étoiles. Dors bien !")]),
]

comptines = [{"id":i,"title":t,"emoji":e,"primary":p,"secondary":s,"lines":l,"melody":m}
             for (i,t,e,p,s,l,m) in COMPTINES]
histoires = [{"id":i,"title":t,"emoji":e,"primary":p,"secondary":s,
              "pages":[{"emoji":pe,"text":px} for (pe,px) in pg]}
             for (i,t,e,p,s,pg) in HISTOIRES]

out = {"comptines":comptines,"histoires":histoires}
dst = os.path.join(os.path.dirname(__file__),"..","src","data","voiceContent.json")
with open(dst,"w",encoding="utf-8") as f:
    json.dump(out,f,ensure_ascii=False,indent=2)
print("voiceContent.json écrit :", len(comptines),"comptines,",len(histoires),"histoires")
